include:
  - remsfal-chat/docker-compose.yml
  - remsfal-platform/docker-compose.yml
services:
  otel-lgtm:
    image: grafana/otel-lgtm
    container_name: otel-lgtm
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
    volumes:
      - otel_data:/data
volumes:
  otel_data:

networks:
  remsfal:
    driver: bridge